const CFG=window.DLLI_CONFIG||{},API_URL=CFG.API_URL||'', $=s=>document.querySelector(s);let token=sessionStorage.getItem('dlli_admin_token')||'',admin=sessionStorage.getItem('dlli_admin_name')||'';let registrations=[];
function ready(){return API_URL&&!API_URL.includes('PASTE_YOUR')}function esc(v){return String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));}function loadBtn(b,on,t='Please wait'){if(on){b.dataset.old=b.innerHTML;b.classList.add('loading');b.innerHTML=`<span class="spinner"></span>${t}`}else{b.classList.remove('loading');b.innerHTML=b.dataset.old||b.innerHTML}}function msg(el,type,text){el.className=`status-box show status-${type}`;el.textContent=text}
async function get(action,p={}){if(!ready())throw Error('Set Apps Script Web App URL in config.js first.');const u=new URL(API_URL);u.searchParams.set('action',action);if(token)u.searchParams.set('token',token);Object.entries(p).forEach(([k,v])=>u.searchParams.set(k,v??''));const r=await fetch(u.toString(),{redirect:'follow'}),j=await r.json();if(!j.ok)throw Error(j.message||'Request failed');return j}
async function post(action,d={}){if(!ready())throw Error('Set Apps Script Web App URL in config.js first.');const body=new URLSearchParams({action,...d});if(token)body.set('token',token);const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body,redirect:'follow'}),j=await r.json();if(!j.ok)throw Error(j.message||'Request failed');return j}
function openAdmin(){ $('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');$('#adminIdentity').textContent=admin;loadDashboard();}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const b=$('#loginBtn');loadBtn(b,true,'Logging in');try{const d=Object.fromEntries(new FormData(e.currentTarget).entries()),r=await post('adminLogin',d);token=r.token;admin=r.admin.name;sessionStorage.setItem('dlli_admin_token',token);sessionStorage.setItem('dlli_admin_name',admin);openAdmin();}catch(x){msg($('#loginMsg'),'error',x.message)}finally{loadBtn(b,false)}})
$('#logoutBtn').onclick=async()=>{try{await post('adminLogout')}catch{}sessionStorage.clear();location.reload()};
document.querySelectorAll('.side-menu button[data-panel]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.side-menu button[data-panel]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$('#panel-'+b.dataset.panel).classList.add('active');$('#topTitle').textContent=b.textContent;if(b.dataset.panel==='registrations')loadRegistrations();if(b.dataset.panel==='sessions')loadSessions();if(b.dataset.panel==='faculty')loadFaculty();if(b.dataset.panel==='settings')loadSettings();});
async function loadDashboard(){try{const r=await get('adminDashboard'),s=r.stats;$('#stTotal').textContent=s.total;$('#stPending').textContent=s.pending;$('#stApproved').textContent=s.approved;$('#stWaiting').textContent=s.waiting;$('#recentBody').innerHTML=(r.recent||[]).map(x=>`<tr><td>${esc(x.Registration_ID)}</td><td>${esc(x.Full_Name)}</td><td>${esc(x.Club_Name)}</td><td>${esc(x.Mobile)}</td><td>${badge(x.Status)}</td></tr>`).join('')||'<tr><td colspan="5">No registrations yet.</td></tr>';}catch(e){alert(e.message)}}
function badge(s){const c=String(s||'pending').toLowerCase();return `<span class="badge ${esc(c)}">${esc(s||'PENDING')}</span>`}
async function loadRegistrations(){try{const r=await get('adminListRegistrations');registrations=r.rows||[];renderRegs()}catch(e){alert(e.message)}}
function renderRegs(){const f=$('#regFilter').value,q=$('#regSearch').value.toLowerCase();const rows=registrations.filter(x=>(f==='ALL'||x.Status===f)&&(!q||[x.Full_Name,x.Lions_ID,x.Club_Name,x.Mobile,x.Registration_ID].join(' ').toLowerCase().includes(q)));$('#regsBody').innerHTML=rows.map(x=>`<tr><td>${esc(x.Registration_ID)}${x.DLLI_ID?`<br><small>${esc(x.DLLI_ID)}</small>`:''}</td><td>${esc(x.Full_Name)}</td><td>${esc(x.Lions_ID)}</td><td>${esc(x.Club_Name)}</td><td>${esc(x.Mobile)}</td><td>${badge(x.Status)}</td><td><div class="row-actions"><button class="btn btn-success mini" onclick="setReg('${esc(x.Registration_ID)}','APPROVED')">Approve</button><button class="btn btn-light mini" onclick="setReg('${esc(x.Registration_ID)}','WAITING_LIST')">Waiting</button><button class="btn btn-danger mini" onclick="setReg('${esc(x.Registration_ID)}','REJECTED')">Reject</button></div></td></tr>`).join('')||'<tr><td colspan="7">No matching registrations.</td></tr>'}
$('#regFilter').onchange=renderRegs;$('#regSearch').oninput=renderRegs;window.setReg=async(id,status)=>{if(!confirm(`Change ${id} to ${status}?`))return;try{await post('adminUpdateRegistration',{registrationId:id,status});await loadRegistrations();await loadDashboard()}catch(e){alert(e.message)}};
$('#refreshDashboard').onclick=loadDashboard;$('#refreshRegs').onclick=loadRegistrations;
async function loadSessions(){try{const r=await get('adminListSessions');$('#sessionsBody').innerHTML=(r.rows||[]).map(x=>`<tr><td>${esc(x.Session_Number)}</td><td>${esc(x.Session_Title)}</td><td>${esc(x.Date)}</td><td>${esc(x.Start_Time)} - ${esc(x.End_Time)}</td><td>${esc(x.Faculty_Name)}</td><td>${esc(x.Hall)}</td><td>${badge(x.Status)}</td></tr>`).join('')||'<tr><td colspan="7">No sessions.</td></tr>'}catch(e){alert(e.message)}}
async function loadFaculty(){try{const r=await get('adminListFaculty');$('#facultyBody').innerHTML=(r.rows||[]).map(x=>`<tr><td>${esc(x.Faculty_ID)}</td><td>${esc(x.Faculty_Name)}</td><td>${esc(x.Designation)}</td><td>${esc(x.Club_Name)}</td><td>${esc(x.Phone)}</td><td>${badge(x.Status)}</td></tr>`).join('')||'<tr><td colspan="6">No faculty.</td></tr>'}catch(e){alert(e.message)}}
async function loadSettings(){try{const r=await get('adminGetSettings');const keys=['INSTITUTE_NAME','INSTITUTE_YEAR','INSTITUTE_DATE_FROM','INSTITUTE_DATE_TO','VENUE','VENUE_MAP_URL','REGISTRATION_OPEN','REGISTRATION_DEADLINE','MAX_PARTICIPANTS','CERTIFICATE_MIN_ATTENDANCE','CONTACT_PHONE','CONTACT_EMAIL','WHATSAPP_NUMBER','NOTICE_MARQUEE','SYSTEM_STATUS'];$('#settingsGrid').innerHTML=keys.map(k=>`<div class="field"><label>${esc(k.replaceAll('_',' '))}</label>${['REGISTRATION_OPEN','SYSTEM_STATUS'].includes(k)?selectSetting(k,r.settings[k]||''): `<input data-setting="${k}" value="${esc(r.settings[k]||'')}">`}</div>`).join('')}catch(e){alert(e.message)}}
function selectSetting(k,v){const opts=k==='REGISTRATION_OPEN'?['YES','NO']:['ACTIVE','MAINTENANCE'];return `<select data-setting="${k}">${opts.map(o=>`<option ${o===v?'selected':''}>${o}</option>`).join('')}</select>`}
$('#saveSettingsBtn').onclick=async()=>{const b=$('#saveSettingsBtn'),obj={};document.querySelectorAll('[data-setting]').forEach(x=>obj[x.dataset.setting]=x.value);loadBtn(b,true,'Saving');try{await post('adminSaveSettings',{settings:JSON.stringify(obj)});alert('Settings saved.')}catch(e){alert(e.message)}finally{loadBtn(b,false)}};
function openModal(title,fields,onSave){$('#modalTitle').textContent=title;$('#modalFields').innerHTML=fields.map(f=>`<div class="field ${f.full?'full':''}"><label>${esc(f.label)}</label>${f.type==='select'?`<select name="${f.name}">${f.options.map(o=>`<option>${esc(o)}</option>`).join('')}</select>`:`<input name="${f.name}" type="${f.type||'text'}" ${f.required?'required':''}>`}</div>`).join('');$('#dataModal').classList.add('show');$('#modalForm').onsubmit=async e=>{e.preventDefault();const b=$('#modalSave');loadBtn(b,true,'Saving');try{await onSave(Object.fromEntries(new FormData(e.currentTarget).entries()));$('#dataModal').classList.remove('show');e.currentTarget.reset()}catch(x){msg($('#modalMsg'),'error',x.message)}finally{loadBtn(b,false)}}}
$('#modalClose').onclick=()=>$('#dataModal').classList.remove('show');
$('#addSessionBtn').onclick=()=>openModal('Add Session',[{label:'Session Number',name:'sessionNumber',required:true},{label:'Session Title',name:'sessionTitle',required:true},{label:'Date',name:'date',type:'date',required:true},{label:'Start Time',name:'startTime',type:'time',required:true},{label:'End Time',name:'endTime',type:'time'},{label:'Faculty Name',name:'facultyName'},{label:'Hall',name:'hall'},{label:'Status',name:'status',type:'select',options:['ACTIVE','INACTIVE','COMPLETED','CANCELLED']}],async d=>{await post('adminSaveSession',d);await loadSessions()});
$('#addFacultyBtn').onclick=()=>openModal('Add Faculty',[{label:'Lions ID',name:'lionsId'},{label:'Faculty Name',name:'facultyName',required:true},{label:'Designation',name:'designation'},{label:'Club Name',name:'clubName'},{label:'Phone',name:'phone'},{label:'Email',name:'email',type:'email'},{label:'Status',name:'status',type:'select',options:['ACTIVE','INACTIVE']}],async d=>{await post('adminSaveFaculty',d);await loadFaculty()});
(async()=>{if(token){try{const r=await get('adminValidate');admin=r.admin.name;openAdmin()}catch{sessionStorage.clear()}}})();
